version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: aoms_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: aoms_db
    volumes:
      - my_postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  my_postgres_data:

    # psql -h localhost -p 5432 -d aoms_db -U admin