spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aoms
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: email-smtp.eu-north-1.amazonaws.com
    username: AKIA6GBMHE665MJ2HAAB
    password: BJbWjnZCuz07krN3bhdXBWSErvy3m9iZHJ0rWKILzGBM
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587
server:
  port: 8080
  servlet:
    context-path: /api
